import type { AppLocale } from "../../i18n/LocaleContext";

export const hubWidgetCopy = {
  ko: {
    communityCategory: "커뮤니티",
    customize: "홈 맞춤 설정",
    done: "변경 사항 저장",
    cancel: "취소",
    saving: "저장 중…",
    editTitle: "나만의 홈을 꾸며보세요.",
    editDescription: "관심 있는 콘텐츠를 추가하고 드래그해 순서를 바꿔보세요.",
    accountStorage: "Renaiss 계정에 저장됩니다",
    localStorage: "이 브라우저에 저장됩니다",
    add: "위젯 추가",
    library: "위젯 모음",
    libraryDescription: "준비된 위젯에서 관심 있는 콘텐츠를 선택하세요.",
    addToHome: "내 홈에 추가",
    alreadyAdded: "홈에 추가됨",
    added: "홈에 추가했습니다",
    editContent: "위젯 설정",
    closeLibrary: "위젯 모음 닫기",
    readyMade: "바로 사용할 수 있어요",
    essentials: "홈 기본 위젯",
    size: "위젯 크기",
    sizes: { small: "작게", medium: "보통", large: "크게" },
    preview: "실제 미리보기",
    previewNote: "홈과 동일한 카드입니다. 모바일에서는 화면 너비에 맞게 표시됩니다.",
    available: "추가 가능",
    restoreHint: "삭제한 위젯은 여기에 남아 있습니다. 언제든 미리 보고 다시 추가하세요.",
    updated: "홈 위젯을 업데이트했습니다",
    updateOnHome: "이 크기 적용",
    hide: "위젯 숨기기",
    drag: "드래그해 순서 변경",
    dragHint: "핸들을 드래그하거나 위·아래 방향키로 한 칸씩 이동하세요. Escape로 이동을 취소할 수 있습니다.",
    max: "최대 8개 위젯",
    project: "프로젝트",
    region: "지역",
    count: "게시물 수",
    loading: "소식을 불러오고 있습니다…",
    error: "현재 소식을 불러올 수 없습니다.",
    retry: "다시 시도",
    empty: "선택한 조건에 맞는 소식이 없습니다.",
    preferencesError: "홈 설정을 불러올 수 없습니다.",
    saveError: "변경 사항을 저장할 수 없습니다. 다시 시도해 주세요.",
    restore: "기본 레이아웃 복원",
    overviewPreset: "기본 홈 레이아웃 사용",
    overviewApplied: "기본 홈 레이아웃을 선택했습니다. 저장하면 홈에 적용됩니다.",
    loadingPreferences: "나의 홈을 불러오고 있습니다…",
    sources: {
      all: "최신 소식",
      official: "공식 소식",
      community: "커뮤니티 이야기",
      events: "활동 소식",
      products: "제품 진행 상황",
    },
    presetDescriptions: {
      all: "Renaiss 커뮤니티의 다양한 소식을 한눈에 확인하세요.",
      official: "Renaiss의 공식 발표를 확인하세요.",
      community: "우리 커뮤니티의 이야기를 만나보세요.",
      events: "활동 공지와 최근 하이라이트.",
      products: "관심 있는 프로젝트의 진행 상황을 확인하세요.",
      member: "나의 Renaiss 프로필, 지갑과 X 계정.",
      questline: "다음 커뮤니티 활동을 위한 공간.",
      merch: "회원 한정 컬렉션을 일상 속으로.",
      partner: "Renaiss × Surf: 계정, X와 Discord 미션.",
    },
    projects: {
      all: "모든 프로젝트",
      tcg: "Renaiss XYZ",
      index: "Renaiss Index",
      defi: "Renaiss DeFi",
      game: "Vinci",
      hackathon: "Taste",
      outreach: "Renaiss Outreach",
    },
    regions: {
      all: "모든 지역",
      global: "글로벌",
      tw: "대만",
      kr: "한국",
      my: "말레이시아",
      vn: "베트남",
      th: "태국",
      multi_region: "여러 지역",
      unknown: "미확인",
    },
    widgets: {
      member: "계정",
      questline: "커뮤니티 미션",
      merch: "굿즈",
      partner: "협업 미션",
      feed: "소식",
    },
  },
  en: {
    communityCategory: "Community",
    customize: "Customize",
    done: "Save changes",
    cancel: "Cancel",
    saving: "Saving…",
    editTitle: "Make it your space.",
    editDescription: "Make a little room for what you love. Drag to rearrange.",
    accountStorage: "Saved to your Renaiss account",
    localStorage: "Saved in this browser",
    add: "Add a widget",
    library: "Widget collection",
    libraryDescription: "Designed for you. Just fill in what you follow.",
    addToHome: "Add to my home",
    alreadyAdded: "On your home",
    added: "Added to your home",
    editContent: "Widget settings",
    closeLibrary: "Close collection",
    readyMade: "Ready to use",
    essentials: "Your essentials",
    size: "Widget size",
    sizes: { small: "Small", medium: "Medium", large: "Large" },
    preview: "Live preview",
    previewNote: "Same card as your home. On mobile, cards fit the screen.",
    available: "Available to add",
    restoreHint: "Removed widgets stay here. Preview and add them again anytime.",
    updated: "Updated on your home",
    updateOnHome: "Apply this size",
    hide: "Hide widget",
    drag: "Drag to rearrange",
    dragHint: "Drag the grip to rearrange. Use the up and down arrow keys to move one position. Escape cancels a drag.",
    max: "Up to 8 widgets",
    project: "Project",
    region: "Region",
    count: "Posts",
    loading: "Loading updates…",
    error: "Updates are temporarily unavailable.",
    retry: "Try again",
    empty: "No updates match these filters yet.",
    preferencesError: "Your layout could not be loaded.",
    saveError: "Changes could not be saved. Please try again.",
    restore: "Restore default layout",
    overviewPreset: "Use overview layout",
    overviewApplied: "Overview selected. Save changes to apply it to your home.",
    loadingPreferences: "Loading your space…",
    sources: {
      all: "Latest updates",
      official: "Official updates",
      community: "Community stories",
      events: "Events",
      products: "Product progress",
    },
    presetDescriptions: {
      all: "A little of everything from the Renaiss community.",
      official: "Announcements, directly from Renaiss.",
      community: "Stories from the community around you.",
      events: "Activity announcements and recent highlights.",
      products: "Follow the progress of a project you love.",
      member: "Your Renaiss identity, wallet and X account.",
      questline: "A home for your next community adventure.",
      merch: "Members’ editions, brought into the everyday.",
      partner: "Renaiss × Surf: accounts, X and Discord tasks.",
    },
    projects: {
      all: "All projects",
      tcg: "Renaiss XYZ",
      index: "Renaiss Index",
      defi: "Renaiss DeFi",
      game: "Vinci",
      hackathon: "Taste",
      outreach: "Renaiss Outreach",
    },
    regions: {
      all: "All regions",
      global: "Global",
      tw: "Taiwan",
      kr: "Korea",
      my: "Malaysia",
      vn: "Vietnam",
      th: "Thailand",
      multi_region: "Multi-region",
      unknown: "Unconfirmed",
    },
    widgets: {
      member: "Account",
      questline: "Questline",
      merch: "Merch",
      partner: "Partner quest",
      feed: "Updates",
    },
  },
  "zh-TW": {
    communityCategory: "Community",
    customize: "自訂首頁",
    done: "儲存變更",
    cancel: "取消",
    saving: "儲存中…",
    editTitle: "把這裡，變成你的首頁。",
    editDescription: "把喜歡的內容放進來，按住小工具拖曳調整順序。",
    accountStorage: "儲存至你的 Renaiss 帳號",
    localStorage: "儲存在這個瀏覽器",
    add: "新增 widget",
    library: "小工具收藏庫",
    libraryDescription: "版型已經準備好，只要填入你關注的內容。",
    addToHome: "加入我的首頁",
    alreadyAdded: "已在首頁",
    added: "已加入首頁",
    editContent: "調整小工具",
    closeLibrary: "收起收藏庫",
    readyMade: "已為你準備好",
    essentials: "首頁小工具",
    size: "小工具尺寸",
    sizes: { small: "小", medium: "中", large: "大" },
    preview: "實際預覽",
    previewNote: "與首頁相同的卡片。手機上會自動符合螢幕寬度。",
    available: "可加入",
    restoreHint: "移除的小工具會留在這裡，隨時預覽、重新加入。",
    updated: "已更新首頁尺寸",
    updateOnHome: "套用這個尺寸",
    hide: "隱藏 widget",
    drag: "拖曳排序",
    dragHint: "拖曳握把可調整順序，也可用鍵盤上下方向鍵移動一格。Escape 可取消拖曳。",
    max: "最多 8 個 widget",
    project: "專案",
    region: "地區",
    count: "篇數",
    loading: "正在讀取動態…",
    error: "目前無法讀取最新動態。",
    retry: "再試一次",
    empty: "目前沒有符合篩選的動態。",
    preferencesError: "目前無法讀取你的首頁設定。",
    saveError: "變更尚未儲存，請再試一次。",
    restore: "恢復預設排版",
    overviewPreset: "套用一屏總覽",
    overviewApplied: "已選擇一屏總覽，儲存後會套用到首頁。",
    loadingPreferences: "正在讀取你的首頁…",
    sources: {
      all: "最新動態",
      official: "官方動態",
      community: "社群故事",
      events: "活動消息",
      products: "產品進度",
    },
    presetDescriptions: {
      all: "來自 Renaiss 社群的消息，一次看見。",
      official: "第一時間，收到 Renaiss 的正式消息。",
      community: "看看你所在的社群，正在發生什麼。",
      events: "活動公告與近期回顧。",
      products: "選一個專案，關注每一步新的進展。",
      member: "你的 Renaiss 身分、錢包與 X 帳號。",
      questline: "為下一段社群參與旅程，留一個位置。",
      merch: "把會員限定的收藏，帶進你的日常。",
      partner: "Renaiss × Surf：帳號、X 與 Discord 合作任務。",
    },
    projects: {
      all: "所有專案",
      tcg: "Renaiss XYZ",
      index: "Renaiss Index",
      defi: "Renaiss DeFi",
      game: "Vinci",
      hackathon: "Taste",
      outreach: "Renaiss Outreach",
    },
    regions: {
      all: "所有地區",
      global: "全球",
      tw: "台灣",
      kr: "韓國",
      my: "馬來西亞",
      vn: "越南",
      th: "泰國",
      multi_region: "跨地區",
      unknown: "待確認",
    },
    widgets: {
      member: "你的身分",
      questline: "社群任務",
      merch: "Merch",
      partner: "合作任務",
      feed: "最新動態",
    },
  },
} as const satisfies Record<AppLocale, object>;

export type HubWidgetCopy = (typeof hubWidgetCopy)[AppLocale];
