import type { AppLocale } from "../../i18n/LocaleContext";

export const hubWidgetCopy = {
  en: {
    customize: "Customize",
    done: "Save changes",
    cancel: "Cancel",
    saving: "Saving…",
    editTitle: "Make it your space.",
    editDescription: "Make a little room for what you love. Drag to rearrange.",
    accountStorage: "Saved to your Renaiss account",
    localStorage: "Saved in this browser",
    add: "Add a widget",
    library: "Widget collection",
    libraryDescription: "Designed for you. Just fill in what you follow.",
    addToHome: "Add to my home",
    alreadyAdded: "On your home",
    added: "Added to your home",
    editContent: "Widget settings",
    closeLibrary: "Close collection",
    readyMade: "Ready to use",
    essentials: "Your essentials",
    size: "Widget size",
    sizes: { small: "Small", medium: "Medium", large: "Large" },
    preview: "Live preview",
    previewNote: "Same card as your home. On mobile, cards fit the screen.",
    available: "Available to add",
    restoreHint: "Removed widgets stay here. Preview and add them again anytime.",
    updated: "Updated on your home",
    updateOnHome: "Apply this size",
    hide: "Hide widget",
    drag: "Drag to rearrange",
    dragHint: "Drag the grip to rearrange. Use the up and down arrow keys to move one position. Escape cancels a drag.",
    max: "Up to 8 widgets",
    project: "Project",
    region: "Region",
    count: "Posts",
    loading: "Loading updates…",
    error: "Updates are temporarily unavailable.",
    retry: "Try again",
    empty: "No updates match these filters yet.",
    website: "Open Community Hub",
    preferencesError: "Your layout could not be loaded.",
    saveError: "Changes could not be saved. Please try again.",
    restore: "Restore default layout",
    overviewPreset: "Use overview layout",
    overviewApplied: "Overview selected. Save changes to apply it to your home.",
    loadingPreferences: "Loading your space…",
    sources: {
      all: "Latest updates",
      official: "Official updates",
      community: "Community stories",
      events: "Events",
      products: "Product progress",
    },
    presetDescriptions: {
      all: "A little of everything from the Renaiss community.",
      official: "Announcements, directly from Renaiss.",
      community: "Stories from the community around you.",
      events: "Activity announcements and recent highlights.",
      products: "Follow the progress of a project you love.",
      member: "Your Renaiss identity, wallet and X account.",
      questline: "A home for your next community adventure.",
      merch: "Members’ editions, brought into the everyday.",
      partner: "Renaiss × Surf: accounts, X and Discord tasks.",
    },
    projects: {
      all: "All projects",
      tcg: "Renaiss XYZ",
      index: "Renaiss Index",
      defi: "Renaiss DeFi",
      game: "Vinci",
      hackathon: "Taste",
      outreach: "Renaiss Outreach",
    },
    regions: {
      all: "All regions",
      global: "Global",
      tw: "Taiwan",
      kr: "Korea",
      my: "Malaysia",
      vn: "Vietnam",
      th: "Thailand",
      multi_region: "Multi-region",
      unknown: "Unconfirmed",
    },
    widgets: {
      member: "Account",
      questline: "Questline",
      merch: "Merch",
      partner: "Partner quest",
      feed: "Updates",
    },
  },
  "zh-TW": {
    customize: "自訂首頁",
    done: "儲存變更",
    cancel: "取消",
    saving: "儲存中…",
    editTitle: "把這裡，變成你的首頁。",
    editDescription: "把喜歡的內容放進來，按住小工具拖曳調整順序。",
    accountStorage: "儲存至你的 Renaiss 帳號",
    localStorage: "儲存在這個瀏覽器",
    add: "新增 widget",
    library: "小工具收藏庫",
    libraryDescription: "版型已經準備好，只要填入你關注的內容。",
    addToHome: "加入我的首頁",
    alreadyAdded: "已在首頁",
    added: "已加入首頁",
    editContent: "調整小工具",
    closeLibrary: "收起收藏庫",
    readyMade: "已為你準備好",
    essentials: "首頁小工具",
    size: "小工具尺寸",
    sizes: { small: "小", medium: "中", large: "大" },
    preview: "實際預覽",
    previewNote: "與首頁相同的卡片。手機上會自動符合螢幕寬度。",
    available: "可加入",
    restoreHint: "移除的小工具會留在這裡，隨時預覽、重新加入。",
    updated: "已更新首頁尺寸",
    updateOnHome: "套用這個尺寸",
    hide: "隱藏 widget",
    drag: "拖曳排序",
    dragHint: "拖曳握把可調整順序，也可用鍵盤上下方向鍵移動一格。Escape 可取消拖曳。",
    max: "最多 8 個 widget",
    project: "專案",
    region: "地區",
    count: "篇數",
    loading: "正在讀取動態…",
    error: "目前無法讀取最新動態。",
    retry: "再試一次",
    empty: "目前沒有符合篩選的動態。",
    website: "前往 Community Hub",
    preferencesError: "目前無法讀取你的首頁設定。",
    saveError: "變更尚未儲存，請再試一次。",
    restore: "恢復預設排版",
    overviewPreset: "套用一屏總覽",
    overviewApplied: "已選擇一屏總覽，儲存後會套用到首頁。",
    loadingPreferences: "正在讀取你的首頁…",
    sources: {
      all: "最新動態",
      official: "官方動態",
      community: "社群故事",
      events: "活動消息",
      products: "產品進度",
    },
    presetDescriptions: {
      all: "來自 Renaiss 社群的消息，一次看見。",
      official: "第一時間，收到 Renaiss 的正式消息。",
      community: "看看你所在的社群，正在發生什麼。",
      events: "活動公告與近期回顧。",
      products: "選一個專案，關注每一步新的進展。",
      member: "你的 Renaiss 身分、錢包與 X 帳號。",
      questline: "為下一段社群參與旅程，留一個位置。",
      merch: "把會員限定的收藏，帶進你的日常。",
      partner: "Renaiss × Surf：帳號、X 與 Discord 合作任務。",
    },
    projects: {
      all: "所有專案",
      tcg: "Renaiss XYZ",
      index: "Renaiss Index",
      defi: "Renaiss DeFi",
      game: "Vinci",
      hackathon: "Taste",
      outreach: "Renaiss Outreach",
    },
    regions: {
      all: "所有地區",
      global: "全球",
      tw: "台灣",
      kr: "韓國",
      my: "馬來西亞",
      vn: "越南",
      th: "泰國",
      multi_region: "跨地區",
      unknown: "待確認",
    },
    widgets: {
      member: "你的身分",
      questline: "社群任務",
      merch: "Merch",
      partner: "合作任務",
      feed: "最新動態",
    },
  },
} as const satisfies Record<AppLocale, object>;

export type HubWidgetCopy = (typeof hubWidgetCopy)[AppLocale];
