export function missionErrorCopy(code: string, zh: boolean) {
  const messages: Record<string, [string, string]> = {
    renaiss_x_not_linked: ['請先在 Renaiss 綁定 X，再重新登入。', 'Link X in Renaiss, then sign in again.'],
    renaiss_x_mismatch: ['請授權與 Renaiss 綁定相同的 X 帳號。', 'Authorize the X account linked to Renaiss.'],
    social_account_already_connected: ['此帳號已連接另一位參加者。', 'This account is linked to another participant.'],
    social_authorization_cancelled: ['授權已取消，可再次連接。', 'Authorization cancelled. You can reconnect.'],
    invalid_social_oauth_state: ['授權已失效，請重新連接。', 'Authorization expired. Please reconnect.'],
    mission_check_busy: ['請稍候再試，避免重複查核。', 'Please wait a moment before checking again.'],
    provider_rate_limited: ['平台暫時限流，請稍後重試。', 'The platform is rate limiting requests. Try again later.'],
    provider_access_denied: ['平台未允許查核，請稍後重試。', 'The platform did not permit this check. Try again later.'],
    following_check_incomplete: ['追蹤清單尚未查完，請稍後重新驗證。', 'The following list check did not finish. Please try again.'],
    not_following: ['尚未追蹤 Surf，追蹤後按驗證。', 'Follow Surf, then verify again.'],
    not_a_member: ['尚未加入 Surf，加入後按驗證。', 'Join Surf, then verify again.'],
    membership_screening_pending: ['請先完成 Surf 伺服器的規則確認。', 'Complete Surf’s server membership screening.'],
    authorization_expired: ['授權已失效，請重新連接。', 'Authorization expired. Please reconnect.'],
    permission_required: ['需要重新授權查核權限。', 'Reconnect to grant verification access.'],
    connection_required: ['請先連接帳號。', 'Connect your account first.'],
    unauthenticated: ['請重新登入 Renaiss。', 'Please sign in to Renaiss again.'],
    demo_missions_disabled: ['Demo 無法驗證活動任務。', 'Demo cannot verify campaign tasks.'],
    mission_state_unavailable: ['任務狀態讀取失敗，請重試。', 'Could not load task status. Try again.'],
    renaiss_email_missing: ['Renaiss 未提供登入信箱，請先綁定信箱後重新登入。', 'Add an email to Renaiss, then sign in again.'],
    renaiss_email_invalid: ['Renaiss 回傳的信箱格式不正確，請到帳號設定確認，再重新登入。', 'Renaiss returned an invalid email. Check account settings, then sign in again.'],
    renaiss_email_changed: ['登入信箱已變更，請重新登入後驗證。', 'Your sign-in email changed. Sign in again before verifying.'],
    surf_email_invalid: ['Renaiss 回傳的信箱格式不正確，請到帳號設定確認。', 'Check the email in Renaiss account settings.'],
    surf_not_registered: ['Surf 未找到此信箱的有效帳號。請以相同信箱登入或註冊 Surf 後重新驗證。', 'Surf found no active account for this email. Sign in or register with the same email, then recheck.'],
    surf_account_already_connected: ['此 Surf 信箱已用於另一個 Renaiss 參加帳號。', 'This Surf email is already linked to another Renaiss participant.'],
    surf_not_configured: ['Surf 查核尚未設定完成，請稍後再試。', 'Surf verification is not configured yet. Please try later.'],
    surf_key_configuration_conflict: ['Surf 查核設定有誤，需要管理者處理。', 'Surf verification needs an administrator to fix its configuration.'],
    surf_key_file_unavailable: ['Surf 查核設定有誤，需要管理者處理。', 'Surf verification needs an administrator to fix its configuration.'],
    surf_key_invalid: ['Surf 查核設定有誤，需要管理者處理。', 'Surf verification needs an administrator to fix its configuration.'],
    surf_partner_key_rejected: ['Surf 查核憑證已失效，需要管理者更新。', 'The Surf verification credential was rejected. An administrator must update it.'],
    surf_rate_limited: ['Surf 暫時限流，請依提示時間重試。', 'Surf is rate limiting checks. Retry after the indicated time.'],
    surf_provider_unreachable: ['暫時連不上 Surf，請稍後重試。', 'Could not reach Surf. Please try again later.'],
    surf_email_rejected: ['Surf 無法查核此登入信箱，請稍後重試或聯絡支援。', 'Surf could not check this sign-in email. Try again later or contact support.'],
    surf_provider_error: ['Surf 服務暫時無法查核，請稍後重試。', 'Surf verification is temporarily unavailable. Please try again later.'],
    surf_response_invalid: ['Surf 回傳的查核資料不完整，請稍後重試。', 'Surf returned an invalid verification response. Please try again later.'],
  };
  const pair = messages[code];
  return pair ? pair[zh ? 0 : 1] : zh ? '暫時無法完成查核，請稍後重試。' : 'Verification is unavailable. Please try again later.';
}
