import type { AppLocale } from "../../i18n/LocaleContext";

export const renaissHubCopy = {
  ko: {
    dashboardLabel: "나의 홈 위젯",
    preview: "디자인 미리보기",
    introduction: {
      eyebrow: "회원 공간",
      title: "나의 Renaiss",
      description: "계정, 커뮤니티 미션과 회원 한정 컬렉션.",
    },
    member: {
      eyebrow: "계정",
      title: "나의 프로필",
      disconnected: "Renaiss에 오신 것을 환영합니다.",
      description: "Renaiss 계정을 연결하고 시작하세요.",
      loading: "계정을 확인하고 있습니다…",
      error: "계정을 불러올 수 없습니다.",
      retry: "다시 시도",
      login: "계정 연결",
      connected: "연결됨",
      wallet: "Safe 지갑",
      x: "X 계정",
      unavailable: "연결 후 확인",
      missingWallet: "연결된 지갑 없음",
      missingX: "연결된 X 계정 없음",
      accountLabel: "Renaiss 계정",
      avatar: "프로필 사진",
      noAvatar: "프로필 사진 없음",
      avatarError: "사진을 불러올 수 없음",
      sbt: "SBT 배지",
      sbtLoading: "보유 수량 확인 중…",
      sbtError: "보유 수량을 불러올 수 없습니다",
      sbtPreview: "추가 후 보유 수량 확인",
      sbtDemo: "데모 계정",
      sbtRefresh: "SBT 새로고침",
      sbtCheckedAt: "확인 시각",
      email: "이메일",
      emailMissing: "이메일 연결",
      emailSettings: "Renaiss 설정에서 이메일을 연결한 후 다시 로그인해 동기화하세요",
      xSettings: "Renaiss 설정에서 X를 연결한 후 다시 로그인하세요",
      syncAccount: "계정 동기화",
      syncHint: "다시 로그인하면 최신 계정 정보를 가져옵니다",
      copyWallet: "Safe 지갑 주소 복사",
      copiedWallet: "지갑 주소를 복사했습니다",
      copyError: "복사하지 못했습니다. 다시 시도해 주세요.",
    },
    questline: {
      eyebrow: "커뮤니티 미션",
      title: "커뮤니티 미션을 만나보세요.",
      stage: "곧 공개됩니다",
      description:
        "새로운 커뮤니티와 만나 활동에 참여하고 참여 기록을 남겨보세요.",
      steps: [
        { title: "연결", description: "나의 Renaiss 프로필" },
        { title: "참여", description: "인증된 커뮤니티 활동" },
        { title: "수집", description: "활동 규칙에 따른 보상" },
      ],
      disclosure: "미션은 어떻게 진행되나요?",
      note: "연결된 계정의 활동을 확인하고 결과를 기록합니다. 미리보기에서는 미션과 보상이 활성화되지 않습니다.",
    },
    merch: {
      eyebrow: "회원 한정 컬렉션",
      title: "Renaiss Merch",
      description: "한정 컬렉션을 일상 속으로.",
      action: "굿즈 둘러보기",
      preparing: "준비 중",
      error: "스토어 콘텐츠를 준비하지 못했습니다. 다시 시도해 주세요.",
      imageAlt: "미개봉 Renaiss 한정 굿즈",
    },
    community: {
      eyebrow: "커뮤니티",
      title: "커뮤니티 소식",
      channel: "Renaiss Community",
      description:
        "새로운 협업, 커뮤니티 이야기와 함께 나누고 싶은 소식.",
      note: "커뮤니티 소식이 연결되면 여기에 표시됩니다.",
      status: "소식 준비 중",
    },
    footer: "RENAISS · 연결 / 참여 / 수집",
  },
  en: {
    dashboardLabel: "Your home widgets",
    preview: "Design preview",
    introduction: {
      eyebrow: "Member space",
      title: "Your Renaiss",
      description: "Your account, community quests, and members’ editions.",
    },
    member: {
      eyebrow: "Account",
      title: "Your identity",
      disconnected: "Welcome to Renaiss.",
      description: "Connect your Renaiss account to get started.",
      loading: "Checking your account…",
      error: "Your account could not be loaded.",
      retry: "Try again",
      login: "Connect account",
      connected: "Connected",
      wallet: "Safe wallet",
      x: "X account",
      unavailable: "Connect to view",
      missingWallet: "No wallet connected",
      missingX: "No X account connected",
      accountLabel: "Renaiss account",
      avatar: "Your profile photo",
      noAvatar: "No profile photo",
      avatarError: "Photo unavailable",
      sbt: "SBT badges",
      sbtLoading: "Checking holdings…",
      sbtError: "Holdings could not be loaded",
      sbtPreview: "View holdings after adding",
      sbtDemo: "Demo account",
      sbtRefresh: "Refresh SBT",
      sbtCheckedAt: "Checked",
      email: "Email",
      emailMissing: "Link email",
      emailSettings: "Link your email in Renaiss settings, then sign in again to sync",
      xSettings: "Link X in Renaiss settings, then sign in again",
      syncAccount: "Sync account",
      syncHint: "Sign in again to get the latest account data",
      copyWallet: "Copy Safe wallet address",
      copiedWallet: "Wallet address copied",
      copyError: "Could not copy. Try again.",
    },
    questline: {
      eyebrow: "Questline",
      title: "Explore community quests.",
      stage: "Coming soon",
      description:
        "Meet new communities. Take part in their stories. Keep a record of what you do.",
      steps: [
        { title: "Connect", description: "Your Renaiss identity" },
        { title: "Participate", description: "A verified community action" },
        { title: "Collect", description: "Campaign rewards, when offered" },
      ],
      disclosure: "How quests work",
      note: "A quest checks the connected account’s action and records the result. Tasks and rewards are not active in this preview.",
    },
    merch: {
      eyebrow: "Members’ editions",
      title: "Renaiss Merch",
      description: "Limited objects. Something to carry with you.",
      action: "Explore Merch",
      preparing: "Preparing",
      error: "Store media could not be prepared. Try again.",
      imageAlt: "Sealed Renaiss merchandise edition",
    },
    community: {
      eyebrow: "Community",
      title: "Community updates",
      channel: "Renaiss Community",
      description:
        "New collaborations, community stories, and things worth sharing.",
      note: "Updates will appear here when the community feed is connected.",
      status: "Feed in preparation",
    },
    footer: "RENAISS · CONNECT / PARTICIPATE / COLLECT",
  },
  "zh-TW": {
    dashboardLabel: "你的首頁小工具",
    preview: "設計預覽",
    introduction: {
      eyebrow: "Member space",
      title: "你的 Renaiss",
      description: "帳號、社群任務與限定周邊，一起探索。",
    },
    member: {
      eyebrow: "Account",
      title: "你的身分",
      disconnected: "歡迎來到 Renaiss。",
      description: "連接帳號，開始你的參與旅程。",
      loading: "正在確認帳號…",
      error: "目前無法讀取帳號。",
      retry: "再試一次",
      login: "連接帳號",
      connected: "已連接",
      wallet: "Safe 錢包",
      x: "X 帳號",
      unavailable: "連接後查看",
      missingWallet: "尚未連接錢包",
      missingX: "尚未連接 X",
      accountLabel: "Renaiss 帳號",
      avatar: "你的帳號頭像",
      noAvatar: "尚無帳號頭像",
      avatarError: "頭像無法載入",
      sbt: "SBT 持有徽章",
      sbtLoading: "正在查詢持有數量…",
      sbtError: "持有數量暫時無法讀取",
      sbtPreview: "加入後查看持有數量",
      sbtDemo: "示範帳號",
      sbtRefresh: "刷新 SBT",
      sbtCheckedAt: "查詢時間",
      email: "信箱",
      emailMissing: "綁定信箱",
      emailSettings: "前往 Renaiss 設定綁定信箱，再重新登入同步",
      xSettings: "前往 Renaiss 設定綁定 X，完成後重新登入",
      syncAccount: "同步帳號",
      syncHint: "重新登入取得最新資料",
      copyWallet: "複製 Safe 錢包地址",
      copiedWallet: "錢包地址已複製",
      copyError: "複製失敗，請再試一次。",
    },
    questline: {
      eyebrow: "Questline",
      title: "探索社群任務。",
      stage: "即將推出",
      description: "認識新的社群，參與合作活動，讓每一次連結成為你的故事。",
      steps: [
        { title: "連接帳號", description: "從 Renaiss 身分開始" },
        { title: "參與任務", description: "驗證實際完成的動作" },
        { title: "收藏獎勵", description: "依正式活動規則開放" },
      ],
      disclosure: "任務會怎麼驗證？",
      note: "任務會查核已連接帳號的實際動作，並記錄結果。這個預覽尚未開放任務或獎勵。",
    },
    merch: {
      eyebrow: "Members’ editions",
      title: "Renaiss Merch",
      description: "把收藏的故事，帶進日常。",
      action: "探索 Merch",
      preparing: "正在準備",
      error: "商店素材無法載入，請再試一次。",
      imageAlt: "尚未開封的 Renaiss 限定周邊",
    },
    community: {
      eyebrow: "Community",
      title: "社群最新動態。",
      channel: "Renaiss Community",
      description: "新的合作、社群故事，以及值得分享的消息。",
      note: "串接社群來源後，這裡會顯示最新動態。",
      status: "動態籌備中",
    },
    footer: "RENAISS · CONNECT / PARTICIPATE / COLLECT",
  },
} as const satisfies Record<AppLocale, object>;

export type RenaissHubCopy = (typeof renaissHubCopy)[AppLocale];
