export const surfCampaignCopy = {
  "zh-TW": {
    close: "關閉活動詳情", eyebrow: "PARTNER CAMPAIGN", stage: "活動預覽",
    title: "Renaiss × Surf", description: "Renaiss 收藏社群，攜手 Surf 鏈上 AI 助手。完成聯名任務，抽 Mystery Box 與 Pro 會員。",
    heroLineOne: "重磅聯名。", heroLineTwo: "收藏 × 鏈上 AI。", heroNote: "Renaiss × Surf · 聯名任務與獎品",
    back: "返回總覽", pageLabel: "合作活動", pageNavigation: "活動導覽", language: "語言", viewTasks: "查看任務", viewRewards: "探索獎品",
    boxAlt: "Surf 官方 Mystery Box：黑色盒身、粉色燈邊與股票代幣", proAlt: "Surf 官方 AI 研究產品介面",
    officialVisual: "Surf 官方產品圖", productView: "Surf 產品畫面", entriesPending: "先驗證雙方帳號，再計算任務機會。", entriesVerified: "已驗證任務對應機會",
    details: "活動資訊", sbtValue: "設計與領取方式待公布",
    rewards: "這次有哪些獎品？", planned: "規劃獎池", box: "Surf Mystery Box",
    boxDescription: "內含 1 年 Surf Pro 會員；完整內容依正式公告。",
    trial: "Surf Pro 體驗", trialDescription: "1 個月 Pro 會員，探索美股與加密資產的 AI 研究工具。",
    proFeatures: ["即時問答", "深度研究", "市場資料整理"], proLearnMore: "認識 Surf",
    quantity: "份", rewardNote: "這是合作活動的抽獎獎池。商店兌換配額另計，不包含在這裡。",
    tasks: "怎麼參加", accounts: "擁有 Renaiss + Surf 帳號", accountsDescription: "必做。既有帳號也可參加，無需重複註冊。",
    follow: "追蹤 Surf X", followDescription: "加分。已追蹤的人也可參加。",
    discord: "加入 Surf Discord", discordDescription: "加分。已加入的人也可參加。",
    entry: "1 次", bonus: "+1 次", total: "最多 3 次抽獎機會", rule: "先完成帳號條件，才能累積加分任務的抽獎機會。",
    surf: "前往 Surf", x: "前往 X", join: "前往 Discord", account: "登入 Renaiss",
    connected: "Renaiss 已登入", loading: "正在確認 Renaiss 帳號…", error: "無法確認帳號，請再試一次。", retry: "重試", demo: "Demo 不計入活動資格。",
    verification: "連接帳號，驗證任務", verificationDescription: "登入 Renaiss，驗證 Surf 帳號，再授權 X／Discord 查核。這裡顯示任務對應機會；正式抽獎依活動公告。",
    schedule: "活動時間", scheduleValue: "待正式公告", scheduleDescription: "開放時間、截止日與抽獎日期確認後，會更新在這裡。",
    sbt: "聯名 SBT", sbtDescription: "方案包含聯名 SBT；設計、領取方式與開放時間待公布。",
    linkPending: "正式活動連結待公布", announcement: "查看 Surf 官方 X", openCampaign: "前往正式活動",
    previewNote: "任務查核與領獎分開；獎品依正式活動公告。",
  },
  en: {
    close: "Close campaign details", eyebrow: "PARTNER CAMPAIGN", stage: "Campaign preview",
    title: "Renaiss × Surf", description: "Renaiss joins forces with Surf’s onchain AI assistant. Complete the collaboration quests for a chance to win Mystery Boxes and Pro memberships.",
    heroLineOne: "Collectibles.", heroLineTwo: "Onchain AI.", heroNote: "Renaiss × Surf · Quests & rewards",
    back: "Overview", pageLabel: "Collaboration", pageNavigation: "Campaign navigation", language: "Language", viewTasks: "View quests", viewRewards: "Explore rewards",
    boxAlt: "Official Surf Mystery Box with a black case, pink lighting and tokenized equities", proAlt: "The official Surf AI research interface",
    officialVisual: "Official Surf product artwork", productView: "Surf product view", entriesPending: "Verify both accounts before task entries can be calculated.", entriesVerified: "Verified task entries",
    details: "Campaign details", sbtValue: "Design & claims to be announced",
    rewards: "What’s in the prize pool?", planned: "Planned rewards", box: "Surf Mystery Box",
    boxDescription: "Includes one year of Surf Pro. Full contents to be announced.",
    trial: "Surf Pro trial", trialDescription: "One month of Pro. Explore AI research tools for equities and crypto.",
    proFeatures: ["Instant answers", "Deep research", "Market intelligence"], proLearnMore: "Discover Surf",
    quantity: "available", rewardNote: "These are campaign draw rewards. Store redemption allocations are separate.",
    tasks: "How to participate", accounts: "Have Renaiss + Surf accounts", accountsDescription: "Required. Existing accounts are eligible; no need to register again.",
    follow: "Follow Surf on X", followDescription: "Bonus. Existing followers are eligible too.",
    discord: "Join Surf Discord", discordDescription: "Bonus. Existing members are eligible too.",
    entry: "1 entry", bonus: "+1 entry", total: "Up to 3 draw entries", rule: "Complete the account requirement before bonus tasks count towards your entries.",
    surf: "Open Surf", x: "Open X", join: "Open Discord", account: "Sign in to Renaiss",
    connected: "Signed in to Renaiss", loading: "Checking your account…", error: "Your account could not be checked.", retry: "Try again", demo: "Demo does not count towards eligibility.",
    verification: "Connect accounts. Verify tasks.", verificationDescription: "Sign in to Renaiss, verify your Surf account, then authorize X / Discord checks. This shows your task tally; the official draw follows the campaign announcement.",
    schedule: "Campaign dates", scheduleValue: "To be announced", scheduleDescription: "Launch, deadline and draw dates will appear here once confirmed.",
    sbt: "Collaboration SBT", sbtDescription: "The plan includes a collaboration SBT. Design and claim details are still to be announced.",
    linkPending: "Campaign link to be announced", announcement: "Visit Surf’s official X", openCampaign: "Open the campaign",
    previewNote: "Task verification and reward claims are separate. Rewards follow the final announcement.",
  },
} as const;
