import { surfCampaign } from '../../../shared/surf-campaign.js';

const campaignDate = (value: string) => new Intl.DateTimeFormat('en-CA', {
  timeZone: surfCampaign.timeZone, month: '2-digit', day: '2-digit',
  hour: '2-digit', minute: '2-digit', hourCycle: 'h23',
}).format(new Date(value)).replace(',', '');
const campaignWindow = `${campaignDate(surfCampaign.startsAt)} — ${campaignDate(surfCampaign.endsAt)}`;

export const surfCampaignCopy = {
  "zh-TW": {
    rewardsSection: '01 / REWARDS', questSection: '02 / YOUR QUEST', detailsSection: '03 / GOOD TO KNOW', proKicker: '02 / 1 MONTH',
    close: "關閉活動詳情", eyebrow: "PARTNER CAMPAIGN", stage: "活動預覽",
    title: "Renaiss × Surf", description: "Renaiss 收藏社群，攜手 Surf 鏈上 AI 助手。完成聯名任務，抽 Mystery Box 與 Pro 會員。",
    heroLineOne: "重磅聯名。", heroLineTwo: "收藏 × 鏈上 AI。", heroNote: "Renaiss × Surf · 聯名任務與獎品",
    back: "返回總覽", pageLabel: "合作活動", pageNavigation: "活動導覽", language: "語言", viewTasks: "查看任務", viewRewards: "探索獎品",
    boxAlt: "Surf 官方 Mystery Box：黑色盒身、粉色燈邊與股票代幣", proAlt: "Surf 官方 AI 研究產品介面",
    productView: "Surf 產品畫面", entriesPending: "待查核", entriesVerified: "已確認",
    details: "活動資訊", sbtValue: "完成上述任務即可獲得",
    rewards: "這次有哪些獎品？", planned: "規劃獎池", box: "Surf Mystery Box",
    boxDescription: "內含 1 年 Surf Pro 會員；完整內容依正式公告。",
    trial: "Surf Pro 體驗", trialDescription: "1 個月 Pro 會員，探索美股與加密資產的 AI 研究工具。",
    proFeatures: ["即時問答", "深度研究", "市場資料整理"], proLearnMore: "認識 Surf",
    quantity: "份", rewardNote: "這是合作活動的抽獎獎池。商店兌換配額另計，不包含在這裡。",
    tasks: "怎麼參加", accounts: "擁有 Renaiss + Surf 帳號",
    follow: "追蹤 Surf X", discord: "加入 Surf Discord",
    entry: "1 張票", bonus: "+1 張票", total: "每個任務 1 張，最多 3 張票",
    surf: "前往 Surf", x: "前往 X", join: "前往 Discord", account: "登入 Renaiss",
    error: "無法確認帳號，請再試一次。", retry: "重試",
    schedule: "活動時間", scheduleValue: campaignWindow, scheduleDescription: "台灣時間（UTC+8）・抽獎日期尚未公告。",
    sbt: "聯名 SBT", sbtDescription: "需通過任務驗證。",
    linkPending: "正式活動連結待公布", announcement: "查看 Surf 官方 X", openCampaign: "前往正式活動",
    previewNote: "任務查核與領獎分開；獎品依正式活動公告。",
  },
  ko: {
    rewardsSection: '01 / 경품', questSection: '02 / 나의 미션', detailsSection: '03 / 활동 안내', proKicker: '02 / 1개월',
    close: "활동 상세 정보 닫기", eyebrow: "협업 캠페인", stage: "활동 미리보기",
    title: "Renaiss × Surf", description: "Renaiss 컬렉터 커뮤니티와 온체인 AI 어시스턴트 Surf가 만났습니다. 협업 미션을 완료하고 Mystery Box와 Pro 멤버십 추첨에 참여하세요.",
    heroLineOne: "컬렉션.", heroLineTwo: "온체인 AI.", heroNote: "Renaiss × Surf · 미션과 보상",
    back: "홈", pageLabel: "협업 활동", pageNavigation: "활동 메뉴", language: "언어", viewTasks: "미션 보기", viewRewards: "경품 둘러보기",
    boxAlt: "검은 상자와 분홍빛 조명, 주식 토큰이 담긴 Surf 공식 Mystery Box", proAlt: "Surf 공식 AI 리서치 화면",
    productView: "Surf 제품 화면", entriesPending: "확인 대기", entriesVerified: "확인 완료",
    details: "활동 정보", sbtValue: "위 미션을 완료하면 획득할 수 있습니다",
    rewards: "어떤 경품이 있나요?", planned: "예정 경품", box: "Surf Mystery Box",
    boxDescription: "Surf Pro 1년 이용권이 포함됩니다. 전체 구성은 추후 발표됩니다.",
    trial: "Surf Pro 체험", trialDescription: "Pro 1개월 이용권으로 주식과 암호화폐 AI 리서치 도구를 체험하세요.",
    proFeatures: ["실시간 답변", "심층 리서치", "시장 정보"], proLearnMore: "Surf 알아보기",
    quantity: "개", rewardNote: "협업 활동의 추첨 경품입니다. 스토어 교환 수량은 별도로 운영됩니다.",
    tasks: "참여 방법", accounts: "Renaiss + Surf 계정 보유",
    follow: "X에서 Surf 팔로우", discord: "Surf Discord 참여",
    entry: "응모권 1장", bonus: "응모권 +1장", total: "미션당 응모권 1장 · 최대 3장",
    surf: "Surf로 이동", x: "X로 이동", join: "Discord로 이동", account: "Renaiss 로그인",
    error: "계정을 확인할 수 없습니다.", retry: "다시 시도",
    schedule: "활동 기간", scheduleValue: campaignWindow, scheduleDescription: "대만 시간 (UTC+8) · 추첨일은 추후 발표됩니다.",
    sbt: "협업 SBT", sbtDescription: "미션 인증이 필요합니다.",
    linkPending: "공식 활동 링크는 추후 공개됩니다", announcement: "Surf 공식 X 보기", openCampaign: "활동 보기",
    previewNote: "미션 인증과 경품 수령은 별도로 진행됩니다. 경품은 최종 공식 발표를 따릅니다.",
  },
  en: {
    rewardsSection: '01 / REWARDS', questSection: '02 / YOUR QUEST', detailsSection: '03 / GOOD TO KNOW', proKicker: '02 / 1 MONTH',
    close: "Close campaign details", eyebrow: "PARTNER CAMPAIGN", stage: "Campaign preview",
    title: "Renaiss × Surf", description: "Renaiss joins forces with Surf’s onchain AI assistant. Complete the collaboration quests for a chance to win Mystery Boxes and Pro memberships.",
    heroLineOne: "Collectibles.", heroLineTwo: "Onchain AI.", heroNote: "Renaiss × Surf · Quests & rewards",
    back: "Overview", pageLabel: "Collaboration", pageNavigation: "Campaign navigation", language: "Language", viewTasks: "View quests", viewRewards: "Explore rewards",
    boxAlt: "Official Surf Mystery Box with a black case, pink lighting and tokenized equities", proAlt: "The official Surf AI research interface",
    productView: "Surf product view", entriesPending: "Pending", entriesVerified: "Confirmed",
    details: "Campaign details", sbtValue: "Complete the quests above to earn it",
    rewards: "What’s in the prize pool?", planned: "Planned rewards", box: "Surf Mystery Box",
    boxDescription: "Includes one year of Surf Pro. Full contents to be announced.",
    trial: "Surf Pro trial", trialDescription: "One month of Pro. Explore AI research tools for equities and crypto.",
    proFeatures: ["Instant answers", "Deep research", "Market intelligence"], proLearnMore: "Discover Surf",
    quantity: "available", rewardNote: "These are campaign draw rewards. Store redemption allocations are separate.",
    tasks: "How to participate", accounts: "Have Renaiss + Surf accounts",
    follow: "Follow Surf on X", discord: "Join Surf Discord",
    entry: "1 ticket", bonus: "+1 ticket", total: "1 ticket per task · up to 3 tickets",
    surf: "Open Surf", x: "Open X", join: "Open Discord", account: "Sign in to Renaiss",
    error: "Your account could not be checked.", retry: "Try again",
    schedule: "Campaign dates", scheduleValue: campaignWindow, scheduleDescription: "Taiwan time (UTC+8) · Draw date to be announced.",
    sbt: "Collaboration SBT", sbtDescription: "Quest verification is required.",
    linkPending: "Campaign link to be announced", announcement: "Visit Surf’s official X", openCampaign: "Open the campaign",
    previewNote: "Task verification and reward claims are separate. Rewards follow the final announcement.",
  },
} as const;
